<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'RT',
  'author' => 'Rolustech',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Employee_Management',
  'published_date' => '2016-10-17 09:14:49',
  'type' => 'module',
  'version' => 1476695689,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Employee_Management',
  'beans' => 
  array (
    1 => 
    array (
      'module' => 'RT_Payroll',
      'class' => 'RT_Payroll',
      'path' => 'modules/RT_Payroll/RT_Payroll.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'RT_Employees',
      'class' => 'RT_Employees',
      'path' => 'modules/RT_Employees/RT_Employees.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'RT_Bonus',
      'class' => 'RT_Bonus',
      'path' => 'modules/RT_Bonus/RT_Bonus.php',
      'tab' => true,
    ),
    4 => 
    array (
      'module' => 'RT_Leaves',
      'class' => 'RT_Leaves',
      'path' => 'modules/RT_Leaves/RT_Leaves.php',
      'tab' => true,
    ),
    5 => 
    array (
      'module' => 'RT_Deductables',
      'class' => 'RT_Deductables',
      'path' => 'modules/RT_Deductables/RT_Deductables.php',
      'tab' => true,
    ),
    6 => 
    array (
      'module' => 'RT_Appraisals',
      'class' => 'RT_Appraisals',
      'path' => 'modules/RT_Appraisals/RT_Appraisals.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/rt_employees_rt_leaves_RT_Employees.php',
      'to_module' => 'RT_Employees',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/rt_employees_rt_bonus_RT_Employees.php',
      'to_module' => 'RT_Employees',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/rt_employees_rt_increment_history_RT_Employees.php',
      'to_module' => 'RT_Employees',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/rt_employees_rt_appraisals_RT_Employees.php',
      'to_module' => 'RT_Employees',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/rt_employees_rt_payroll_RT_Employees.php',
      'to_module' => 'RT_Employees',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/rt_employees_rt_deductables_RT_Employees.php',
      'to_module' => 'RT_Employees',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/rt_employees_documents_RT_Employees.php',
      'to_module' => 'RT_Employees',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/rt_employees_rt_employees_RT_Employees.php',
      'to_module' => 'RT_Employees',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/rt_employees_rt_leavesMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/rt_employees_rt_bonusMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/rt_employees_rt_increment_historyMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/rt_employees_rt_appraisalsMetaData.php',
    ),
    4 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/rt_employees_rt_payrollMetaData.php',
    ),
    5 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/rt_employees_rt_deductablesMetaData.php',
    ),
    6 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/rt_employees_documentsMetaData.php',
    ),
    7 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/rt_employees_rt_employeesMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/RT_Increment_History',
      'to' => 'modules/RT_Increment_History',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/RT_Payroll',
      'to' => 'modules/RT_Payroll',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/RT_Employees',
      'to' => 'modules/RT_Employees',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/RT_Bonus',
      'to' => 'modules/RT_Bonus',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/RT_Leaves',
      'to' => 'modules/RT_Leaves',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/RT_Deductables',
      'to' => 'modules/RT_Deductables',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/RT_Appraisals',
      'to' => 'modules/RT_Appraisals',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/RT_Leaves.php',
      'to_module' => 'RT_Leaves',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/RT_Employees.php',
      'to_module' => 'RT_Employees',
      'language' => 'en_us',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/RT_Bonus.php',
      'to_module' => 'RT_Bonus',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/RT_Employees.php',
      'to_module' => 'RT_Employees',
      'language' => 'en_us',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/RT_Increment_History.php',
      'to_module' => 'RT_Increment_History',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/RT_Employees.php',
      'to_module' => 'RT_Employees',
      'language' => 'en_us',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/RT_Appraisals.php',
      'to_module' => 'RT_Appraisals',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/RT_Employees.php',
      'to_module' => 'RT_Employees',
      'language' => 'en_us',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/RT_Payroll.php',
      'to_module' => 'RT_Payroll',
      'language' => 'en_us',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/RT_Employees.php',
      'to_module' => 'RT_Employees',
      'language' => 'en_us',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/RT_Deductables.php',
      'to_module' => 'RT_Deductables',
      'language' => 'en_us',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/RT_Employees.php',
      'to_module' => 'RT_Employees',
      'language' => 'en_us',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Documents.php',
      'to_module' => 'Documents',
      'language' => 'en_us',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/RT_Employees.php',
      'to_module' => 'RT_Employees',
      'language' => 'en_us',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/RT_Employees.php',
      'to_module' => 'RT_Employees',
      'language' => 'en_us',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/rt_employees_rt_leaves_RT_Leaves.php',
      'to_module' => 'RT_Leaves',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/rt_employees_rt_leaves_RT_Employees.php',
      'to_module' => 'RT_Employees',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/rt_employees_rt_bonus_RT_Bonus.php',
      'to_module' => 'RT_Bonus',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/rt_employees_rt_bonus_RT_Employees.php',
      'to_module' => 'RT_Employees',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/rt_employees_rt_increment_history_RT_Increment_History.php',
      'to_module' => 'RT_Increment_History',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/rt_employees_rt_increment_history_RT_Employees.php',
      'to_module' => 'RT_Employees',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/rt_employees_rt_appraisals_RT_Appraisals.php',
      'to_module' => 'RT_Appraisals',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/rt_employees_rt_appraisals_RT_Employees.php',
      'to_module' => 'RT_Employees',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/rt_employees_rt_payroll_RT_Payroll.php',
      'to_module' => 'RT_Payroll',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/rt_employees_rt_payroll_RT_Employees.php',
      'to_module' => 'RT_Employees',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/rt_employees_rt_deductables_RT_Deductables.php',
      'to_module' => 'RT_Deductables',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/rt_employees_rt_deductables_RT_Employees.php',
      'to_module' => 'RT_Employees',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/rt_employees_documents_Documents.php',
      'to_module' => 'Documents',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/rt_employees_documents_RT_Employees.php',
      'to_module' => 'RT_Employees',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/rt_employees_rt_employees_RT_Employees.php',
      'to_module' => 'RT_Employees',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    3 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    4 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    5 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    6 => 
    array (
      'additional_fields' => 
      array (
        'Documents' => 'rt_employees_documents_name',
      ),
    ),
    7 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);