<?php
if (!defined('sugarEntry') || !sugarEntry)
    die('Not A Valid Entry Point');

require_once('include/MVC/View/SugarView.php');
//require_once('modules/Import/ImportMap.php');

class RT_Performance_ReviewsViewReview extends SugarView {
    /**
     * Constructor
     */

    public function __construct() {
        parent::SugarView();
    }
 /*   public function preDisplay()
    {
        parent::preDisplay(); // TODO: Change the autogenerated stub
        echo '<script type="text/javascript" src="custom/modules/RT_Performance_Reviews/funcs.js"></script>';
    }*/

    /**
     * display the form
     */

    public function display() {

//        $this->ss->assign("test", "test text for");
        $this->ss->assign('drop_options', $this->view_object_map['d_options']);
//        $this->ss->assign('data_form', $this->view_object_map['form_data']);

        echo $this->ss->fetch("custom/modules/RT_Performance_Reviews/tpls/Review_from.tpl");
        echo "Create form for submit questions";
    }
}
?>